version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pongdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: openjdk:latest
    container_name: pong
    ports:
      - "8081:8080"
    volumes:
      - ./target/Pong-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/pongdb
      - DATABASE_USERNAME=myuser
      - DATABASE_PASSWORD=mypassword
    depends_on:
      - postgres

volumes:
  postgres-data:
